spring:
  application:
    name: corporate-benefits
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/corporate_benefits}
    username: ${SPRING_DATASOURCE_USERNAME:corporate}
    password: ${SPRING_DATASOURCE_PASSWORD:corporate}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
